### ISSUE TITLE
Make 'fell' easier to consume

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/fell#4]
Having now tried to use fell seriously, I've found a number of negatives with it:

  1. It's opinionated &mdash; it's unusable without jshamcrest.
  2. It's hard to integrate with because it requires jshamcrest to be available globally before it was loaded, which is difficult to manage in BRJS.
  3. it has an asthetically displeasing API &mdash; e.g. `Log` is not a class but uses an upper-case letter, and `require('fell')` itself does nothing, but should probably be the logger itself.

**Comment by dchambers** [comment]
This is now finally done (commits cfb1ade278eaf678d9efb37b66182611ceb0a0ca to 79f0d316c01cb6e143d4dc876385407b11b231ac).

@andyberry88, would you like to cast your eyes over these changes before I start to make use of them within CT?

**Comment by andyberry88** [comment]
@dchambers looks good :+1:

**Comment by dchambers** [comment]
@andyberry88, not sure if you saw my previous comment on this issue?
